var util = require('util');
var Undertaker = require('undertaker');
var vfs = require('vinyl-fs');
var watch = require('glob-watcher');
var Crawler = require("crawler");
var jsdom = require('jsdom');
const Nightmare = require('nightmare')
var cheerio=require("cheerio");
var fs = require('fs');
var sleep = require('system-sleep');
var r=require("request");
var runAsync = require('run-async');
var async = require("async");



const neo4j = require('neo4j-driver').v1;
var driver = neo4j.driver("bolt://localhost", neo4j.auth.basic("admin", "admin"));

const session = driver.session();


function Gulp() {
  Undertaker.call(this);
  this.watch = this.watch.bind(this);
  this.task = this.task.bind(this);
  this.series = this.series.bind(this);
  this.parallel = this.parallel.bind(this);
  this.registry = this.registry.bind(this);
  this.tree = this.tree.bind(this);
  this.lastRun = this.lastRun.bind(this);
}

util.inherits(Gulp, Undertaker);
Gulp.prototype.src = vfs.src;
Gulp.prototype.dest = vfs.dest;
Gulp.prototype.symlink = vfs.symlink;
Gulp.prototype.watch = function(glob, opt, task) {
  if (typeof opt === 'string' || typeof task === 'string' ||
    Array.isArray(opt) || Array.isArray(task)) {
    throw new Error('watching ' + glob + ': watch task has to be ' +
      'a function (optionally generated by using gulp.parallel ' +
      'or gulp.series)');
  }

  if (typeof opt === 'function') {
    task = opt;
    opt = {};
  }

  opt = opt || {};

  var fn;
  if (typeof task === 'function') {
    fn = this.parallel(task);
  }

  return watch(glob, opt, fn);
};

Gulp.prototype.Gulp = Gulp;

var inst = new Gulp();
module.exports = inst;
var companyid=1;



async.parallel([
    function(callback) { loop(1,10000,"1-10000.txt") },
    function(callback) { loop(10000,20000,"10000-20000.txt") },
    function(callback) { loop(20000,30000,"20000-30000.txt") }
], function(err, results) {
    // optional callback
});


  

function loop(startNum,endNum,filename){
	
const nightmare = Nightmare({ show:false, maxAuthRetries: 3   });
var website="https://www.itjuzi.com/company/"+startNum;
var d = new Date();
var curr_date = d.getDate();
var curr_month = d.getMonth() + 1; //Months are zero based
var curr_year = d.getFullYear();

var datestring= curr_year.toString()+curr_month.toString()+curr_date.toString();

nightmare
  .goto(website)
 .wait('.seo-important-title')
.evaluate(function(){

    return document.body.innerHTML;

}) .end().then(function (body) {
    //  cheerio.load(html);	
fs.appendFile(filename, '\n '+startNum, function (err) {
  if (err) throw err;
  console.log('Saved!');
  
});
if (startNum<endNum){	
startNum++;
loop(startNum,endNum,filename);
}

    })
  .catch(error => {
    console.error('Search failed:', error)
if (startNum<endNum){
startNum++;	
loop(startNum,endNum,filename);
}
  })

}
  